### ISSUE TITLE
stonfield/sfquery.vcx

### ISSUE THREAD

**Issue by IsaacBreuer** [DougHennig/StonefieldDatabaseToolkit#2]
I have a very  old vfp project that has stonfield/sfquery in it , I try to make some changes but cannot find some dependent files like sfquery.h file.
hiw can I get the vfp stonefields/sfquery tolls?
if thats not open source, I am willing to pay, but cut find it on stonfield website

**Comment by DougHennig** [comment]
Since you also sent me an email, I'll reply via email
